# -*- coding: utf-8 -*-
"""Guía 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgzjvMzW6AOmRsL5M69jUoakIpg2EFSr

# Diagrama de fases
"""

import numpy as np
import matplotlib.pyplot as plt

# Ecuación diferencial autónoma
def f(P):
    return P * (P - 1) * (2 - P)

# Valores de P
P_vals = np.linspace(-1, 3, 100)
dPdt = f(P_vals)

plt.figure(figsize=(8,6))
plt.axhline(0, color="gray", linestyle="--")  # línea de referencia

# Dibujar flechas en el eje P
for P0 in [-1, 0, 0.5, 1, 1.5, 2, 2.5]:
    slope = f(P0)
    if slope > 0:
        plt.arrow(P0, 0, 0, 0.2, head_width=0.05, head_length=0.05, color="blue")
    elif slope < 0:
        plt.arrow(P0, 0, 0, -0.2, head_width=0.05, head_length=0.05, color="red")

plt.plot(P_vals, dPdt, label="dP/dt")
plt.title("Diagrama de fase autónomo: dP/dt = P(P-1)(2-P)")
plt.xlabel("P")
plt.ylabel("dP/dt")
plt.legend()
plt.grid(True)
plt.show()

"""# Campo direccional (#3)"""

import numpy as np
import matplotlib.pyplot as plt

# Definimos la ecuación diferencial autónoma
def f(P):
    return P * (P - 1) * (2 - P)

# Rango de valores
t_vals = np.linspace(0, 20, 20)   # tiempo
P_vals = np.linspace(-3, 3, 20)   # variable dependiente

# Malla de puntos
T, P = np.meshgrid(t_vals, P_vals)

# Pendiente en cada punto
dPdt = f(P)

# Cada flecha: avance en t = 1, avance en P = pendiente
U = np.ones_like(dPdt)   # componente horizontal
V = dPdt                 # componente vertical

# Normalizamos para que las flechas tengan tamaño uniforme
N = np.sqrt(U**2 + V**2)
U, V = U/N, V/N

# Dibujamos el campo direccional
plt.figure(figsize=(8,6))
plt.quiver(T, P, U, V, color="black")

plt.title("Campo direccional: dP/dt = P(P-1)(2-P)")
plt.xlabel("t")
plt.ylabel("P")
plt.grid(True)
plt.show()

"""# Condición inicial 3000"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Definimos la ecuación diferencial autónoma
def f(P, t):
    return P * (P - 1) * (2 - P)

# Rango de tiempo
t_vals = np.linspace(0, 0.5, 200)

# Condiciones iniciales específicas
condiciones_iniciales = [3000]

plt.figure(figsize=(8,6))

# Resolver y graficar cada solución
for P0 in condiciones_iniciales:
    sol = odeint(f, P0, t_vals)
    plt.plot(t_vals, sol, label=f"P(0)={P0}")

# Configuración del gráfico
plt.title("Condición inicial 3000")
plt.xlabel("t")
plt.ylabel("P(t)")
plt.legend()
plt.grid(True)
plt.show()

"""# Condición inicial 15000"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Definimos la ecuación diferencial autónoma
def f(P, t):
    return P * (P - 1) * (2 - P)

# Rango de tiempo
t_vals = np.linspace(0, 0.5, 200)

# Condiciones iniciales específicas
condiciones_iniciales = [1500]

plt.figure(figsize=(8,6))

# Resolver y graficar cada solución
for P0 in condiciones_iniciales:
    sol = odeint(f, P0, t_vals)
    plt.plot(t_vals, sol, label=f"P(0)={P0}")

# Configuración del gráfico
plt.title("Condición inicial 1500")
plt.xlabel("t")
plt.ylabel("P(t)")
plt.legend()
plt.grid(True)
plt.show()

"""# Condición inicial 500"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Definimos la ecuación diferencial autónoma
def f(P, t):
    return P * (P - 1) * (2 - P)

# Rango de tiempo
t_vals = np.linspace(0, 0.5, 200)

# Condiciones iniciales específicas
condiciones_iniciales = [500]

plt.figure(figsize=(8,6))

# Resolver y graficar cada solución
for P0 in condiciones_iniciales:
    sol = odeint(f, P0, t_vals)
    plt.plot(t_vals, sol, label=f"P(0)={P0}")

# Configuración del gráfico
plt.title("Condición inicial 500")
plt.xlabel("t")
plt.ylabel("P(t)")
plt.legend()
plt.grid(True)
plt.show()

"""# Condición inicial 900"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Definimos la ecuación diferencial autónoma
def f(P, t):
    return P * (P - 1) * (2 - P)

# Rango de tiempo
t_vals = np.linspace(0, 0.5, 200)

# Condiciones iniciales específicas
condiciones_iniciales = [900]

plt.figure(figsize=(8,6))

# Resolver y graficar cada solución
for P0 in condiciones_iniciales:
    sol = odeint(f, P0, t_vals)
    plt.plot(t_vals, sol, label=f"P(0)={P0}")

# Configuración del gráfico
plt.title("Condición inicial 900")
plt.xlabel("t")
plt.ylabel("P(t)")
plt.legend()
plt.grid(True)
plt.show()